updated mongock link and removed obsolete information
jhipster/jhipster.github.io pull request #1093
Opened 2021-03-06 10:04 UTC by dieppa

### Changes
- Updated mongock link to Mongock page
- Removed obsolete information about Mongo Atlas error, as it shouldn't happen with Mongock
- Removed obsolete information about the intention of replacing Mongobee with Mongock, as it's already replaced

2021-03-07 20:20 UTC, murdos requested changes
Your first intent was correct, you should update the jhipster_7 branch, since mongock is used by jhipster since Sprint Boot 2.3 upgrade, which has never been released, and will be released as part of JHipster 7.
So please reopen https://github.com/jhipster/jhipster.github.io/pull/1092 insteand ;)

2021-03-07 20:21 UTC, closed without merging

2021-03-08 09:27 UTC, dieppa commented
Thanks @murdos, as the change in the generator was done in the main, I thought that. Will do, thanks!

2021-03-08 11:04 UTC, murdos commented
@dieppa : In fact I was wrong, the jhipster_7 has already been merged, as discussed with @pascalgrimaud: https://github.com/jhipster/jhipster.github.io/pull/1086#issuecomment-792363608 😕 
But don't worry, I'll get things sorted https://github.com/jhipster/jhipster.github.io/pull/1086#issuecomment-792574245 ;)

2021-03-08 11:44 UTC, dieppa commented
Thank you @murdos  and @pascalgrimaud