Update relationships.md
jhipster/jhipster.github.io pull request #1136
Opened 2021-05-31 10:53 UTC by wanghengxn

The test results are as described above. 

jhipster -V
INFO! Using JHipster version installed globally
6.10.5

2021-05-31 10:55 UTC, wanghengxn commented
I found that there are too many things wrong with this document. Maybe you should find someone to check it out.

2021-08-30 14:34 UTC, mshima approved these changes

2021-08-30 17:00 UTC, MathieuAA requested changes
Seems like some changes were made to the generation part and this doc hasn't been up to date... :(

2021-08-30 17:00 UTC, MathieuAA commented on pages/jdl/relationships.md
> +another example:
```suggestion
Another example:
```

2021-08-30 17:00 UTC, MathieuAA commented on pages/jdl/relationships.md
> +Not specifying an injected field is the short form of using having an bidirectional relationship.
```suggestion
Not specifying an injected field is the short form of having a bidirectional relationship.
```

2021-08-31 17:23 UTC, merged