Update entities-filtering.md
jhipster/jhipster.github.io pull request #1270
Opened 2023-03-19 13:22 UTC by seerazz

Fix broken link

2023-03-27 13:51 UTC, mraible commented
We should enter an issue to update it again for Hibernate 6 once JHipster 8 is released.

2023-03-27 13:54 UTC, DanielFran requested changes

2023-03-28 03:31 UTC, seerazz reviewed
This look good

2023-03-28 12:27 UTC, DanielFran approved these changes

2023-03-28 12:27 UTC, merged